/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description The mower model + area-type catalogue (``reference.py``), read-only,
         *     the editor's defaults source (ADR-0024).
         */
        get: operations["get_catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Explain
         * @description Explain why the edits in `request.preferences` that are missing from
         *     `request.schedule` were not kept (Iteration 6).
         *
         *     A plain synchronous call, not a job like `/api/solve`: the explain budget (a few
         *     seconds, capped at 60s by `schemas.ExplainRequest`) bounds it directly, so there is
         *     nothing to poll or cancel. FastAPI runs this `def` handler in a worker thread, the
         *     same as every other handler here — it does not block the server's event loop, only
         *     this one request.
         */
        post: operations["post_explain_api_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Scenario Advance
         * @description Advance "now" for the moving horizon (ADR-0042): slide the window forward, fold the
         *     now-past plan into history, hand back the still-future plan as frozen preferences. The
         *     caller then re-solves the returned scenario carrying ``carried``. ``hours`` outside
         *     ``1..horizon_hours`` is a 400.
         */
        post: operations["post_scenario_advance_api_scenario_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/derived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Scenario Derived
         * @description Recompute the derived figures for an edited scenario (ADR-0024). The editor calls
         *     this as the user types; a malformed body is a 422 from request parsing.
         */
        post: operations["post_scenario_derived_api_scenario_derived_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Scenario Template
         * @description A minimal, immediately-solvable scenario for "New scenario…" (ADR-0027).
         *
         *     Nothing is written: this is a *draft* the editor opens. It reaches disk only via
         *     ``PUT /api/scenario/{id}`` or ``POST /api/scenarios``. 200, not 201 — no resource
         *     is created here.
         */
        post: operations["post_scenario_template_api_scenario_template_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenario__scenario_id__get"];
        /**
         * Put Scenario
         * @description Save the edited scenario over the slug ``scenario_id`` — create or overwrite
         *     (ADR-0026). ``scenario.name`` is forced to the slug. A malformed slug is a 400; a
         *     malformed scenario is a 422 from request parsing.
         */
        put: operations["put_scenario_api_scenario__scenario_id__put"];
        post?: never;
        /**
         * Delete Scenario
         * @description Remove a scenario from the library (ADR-0026). 404 if the slug is unknown.
         */
        delete: operations["delete_scenario_api_scenario__scenario_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        /**
         * Create Scenario
         * @description Save the edited scenario under a *new* slug (the "Save as…" path, ADR-0026). A
         *     slug that is already taken is a 409 — use ``PUT`` to overwrite.
         */
        post: operations["create_scenario_api_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Solve */
        post: operations["post_solve_api_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solve/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Solve */
        get: operations["get_solve_api_solve__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solve/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Cancel Solve */
        post: operations["post_cancel_solve_api_solve__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgreementCounts
         * @description How much of what was asked for survived.
         *
         *     ``mower_total`` counts only preferences that named a mower, so ``mower_kept /
         *     mower_total`` is not diluted by time-only preferences that never asked for one.
         */
        AgreementCounts: {
            /**
             * Mower Kept
             * @default 0
             */
            mower_kept: number;
            /**
             * Mower Total
             * @default 0
             */
            mower_total: number;
            /**
             * Time Kept
             * @default 0
             */
            time_kept: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * Area
         * @description A part of the course that must be serviced regularly.
         */
        Area: {
            /** Hole */
            hole: number;
            /**
             * Max Interval
             * @description Maximum hours between two service starts.
             */
            max_interval: number;
            /**
             * Max Services
             * @description Cap on service starts this week — a user-owned requirement (ADR-0024). None means derive it (ADR-0017). Also caps the ground-program size.
             */
            max_services?: number | null;
            /**
             * Min Interval
             * @description Minimum hours between two service starts.
             */
            min_interval: number;
            /**
             * Min Services
             * @description Required minimum service starts this week — a user-owned requirement (ADR-0024). None means derive it (ADR-0017). See docs/known-hazards.md: a hand-set value can make the scenario genuinely UNSAT.
             */
            min_services?: number | null;
            /** Name */
            name: string;
            /**
             * Priority
             * @description 1 = highest priority. The encoding maps priority P to weak-constraint level 5-P (see docs/design-choices.md B4 and ADR-0012). The range is capped at 3 so that level 5-P stays in {4, 3, 2}, strictly above the avoid-zone level (1) and the min-interval level (0); P >= 4 would put a max-interval violation on the same level as an avoid violation. Relax this bound only together with an encoding change.
             */
            priority: number;
            /**
             * Schedule
             * @description Weekly availability, keyed by weekday name (see DAYS).
             */
            schedule: {
                [key: string]: components["schemas"]["DaySchedule"];
            };
            /**
             * Size M2
             * @description Area size. Promoted from the generator source (ADR-0024) so the scenario is self-describing; None for scenarios authored before that. Feeds the default per-(area, mower) duration and the recomputed load factor.
             */
            size_m2?: number | null;
            /** Type */
            type: string;
        };
        /**
         * BaseDuration
         * @description The productive mowing time (whole hours) for one ``(area, mower)`` pair.
         *
         *     Set by the scenario generator (ADR-0013): it derives this from area size and mower
         *     area-capacity instead of the notebook's seeded sampling. When
         *     :attr:`Scenario.base_durations` is populated the completion table uses these numbers
         *     as the base for its no-go/avoid walk; when it is ``None`` the sampling path
         *     (``duration_seed``) still applies, so ``toy_course`` and the notebook are unchanged.
         */
        BaseDuration: {
            /** Area */
            area: string;
            /** Hours */
            hours: number;
            /** Mower */
            mower: string;
        };
        /** Catalog */
        Catalog: {
            /** Area Types */
            area_types: components["schemas"]["CatalogAreaType"][];
            /** Mower Models */
            mower_models: components["schemas"]["CatalogMower"][];
        };
        /** CatalogAreaType */
        CatalogAreaType: {
            /** Cut Height Mm */
            cut_height_mm: number;
            /**
             * Default Size M2
             * @description Typical size for this type (generator's Distributions.area_geo_mean_m2) — the editor's default when adding an area (ADR-0027). A suggestion, never a constraint.
             */
            default_size_m2: number;
            /** Max Interval H */
            max_interval_h: number;
            /** Min Interval H */
            min_interval_h: number;
            /** Name */
            name: string;
            /** Priority */
            priority: number;
        };
        /**
         * CatalogMower
         * @description One mower model from ``reference.py`` — the editor's defaults source
         *     (ADR-0024). ``capable_area_types`` applies the cut-height rule so the frontend never
         *     re-implements it. Suggestions only — the stored scenario value is always the truth.
         */
        CatalogMower: {
            /** Area Capacity M2 Per Day */
            area_capacity_m2_per_day: number;
            /** Capable Area Types */
            capable_area_types: string[];
            /** Max Cut Height Mm */
            max_cut_height_mm: number;
            /** Min Cut Height Mm */
            min_cut_height_mm: number;
            /** Name */
            name: string;
        };
        /**
         * ConflictingTask
         * @description One task from the plan on screen that a dropped edit conflicts with — a member of
         *     the conflict named in :attr:`EditExplanation.conflicts`.
         */
        ConflictingTask: {
            /** Area */
            area: string;
            /** Mower */
            mower?: string | null;
            /** Start */
            start: number;
        };
        /**
         * DaySchedule
         * @description Availability for one weekday.
         */
        DaySchedule: {
            /**
             * Avoid
             * @description Hours a mower should avoid but may use if necessary (daytime play).
             */
            avoid?: [
                number,
                number
            ][];
            /**
             * No Go
             * @description Hours a mower may not operate at all (irrigation, night rules, ...).
             */
            no_go?: [
                number,
                number
            ][];
        };
        /**
         * DroppedPreference
         * @description One half of one preference that could not be expressed, and why.
         *
         *     ``half`` is ``"time"`` or ``"mower"``. Dropping the mower half leaves the time half
         *     standing — the right degradation for "that machine cannot mow this area".
         */
        DroppedPreference: {
            /** Area */
            area: string;
            /**
             * Half
             * @enum {string}
             */
            half: "time" | "mower";
            /** Mower */
            mower?: string | null;
            /** Reason */
            reason: string;
            /** Start */
            start: number;
        };
        /**
         * EditExplanation
         * @description Why one dropped edit — a submitted preference with ``origin`` ``"edited"`` or
         *     ``"added"`` that does not appear in the resulting schedule — was not kept.
         *
         *     **What each outcome means:**
         *
         *     - ``blocked_statically`` — conflicts with a *kept* task's mower or area interval;
         *       found by a plain overlap check, no solver call.
         *     - ``individually_impossible`` — no schedule could ever place this edit, even alone
         *       (a structural conflict the encoding's own hard constraints rule out regardless of
         *       anything else).
         *     - ``conflicts_with`` — conflicts specifically with the kept tasks named in
         *       ``conflicts``, proven by assumption-based refutation over the real forward model.
         *     - ``not_yet_found`` — a schedule keeping this edit alongside every currently-kept task
         *       does exist (checked directly) — but the solve that produced the plan on screen had
         *       not proven optimality. This is the *only* way a "could have been kept" answer can
         *       arise: if the parent solve **had** been proven optimal, a model satisfying this edit
         *       plus everything already kept would mean strictly fewer unmet preferences than the
         *       claimed optimum — a contradiction. So this outcome is a solid signal that searching
         *       longer (or re-solving with this edit pinned) may do better, never an arbitrary tie.
         *     - ``not_determined`` — the explain budget ran out before an answer was reached. Never
         *       a claim that the edit is impossible.
         */
        EditExplanation: {
            /** Area */
            area: string;
            /** Conflicts */
            conflicts?: components["schemas"]["ConflictingTask"][];
            /**
             * Detail
             * @description A short, composable reason — the specific static overlap found, or a plain count for a conflict.
             */
            detail: string;
            /**
             * Minimal
             * @description False if the explain budget ran out before every candidate in `conflicts` could be checked for redundancy — the conflict is still valid, just not proven smallest (the keep-on-timeout degradation rule: an assumption is only ever removed once proven unnecessary, so a timeout can only leave this larger, never wrong).
             * @default true
             */
            minimal: boolean;
            /** Mower */
            mower?: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "blocked_statically" | "individually_impossible" | "conflicts_with" | "not_yet_found" | "not_determined";
            /**
             * Solve Time S
             * @description Wall time this edit's counterfactual check(s) took. None for blocked_statically, which makes no solver call.
             */
            solve_time_s?: number | null;
            /** Start */
            start: number;
        };
        /**
         * ExplainRequest
         * @description Body for ``POST /api/explain`` (Iteration 6). ``preferences`` and ``schedule`` are
         *     the payload and the result of the solve being explained — the same
         *     ``SolvePreferences`` sent to ``POST /api/solve`` and the ``SolveResult.schedule`` it
         *     returned. Never re-solved: a second solve under the ``-t4`` portfolio could return a
         *     different equally-optimal plan (ADR-0007), which would explain a schedule the user is
         *     not looking at.
         */
        ExplainRequest: {
            /**
             * Budget S
             * @description Overall wall-clock deadline for this explanation (expert-mode setting, mirroring `SolveRequest.time_limit_s`). Omit for the default (`explain.DEFAULT_EXPLAIN_BUDGET_S`). Capped at 60s — this is a feasibility check, not a search, and the Stage 1 pilot's worst observed batch was 7.6s.
             */
            budget_s?: number | null;
            /** @description The edits submitted to the solve being explained. */
            preferences: components["schemas"]["SolvePreferences"];
            /**
             * Released
             * @description Area name -> count of tasks released from it before this re-solve (out of the payload, ADR-0035 decision 3). Never derivable from `preferences` alone — a release is the absence of a task, not a value in it — so the frontend, the only side that knows what was released, sends it explicitly. Lets the `reinstated` explanation compare against the plan before the re-solve rather than the payload alone, so a released service the area's own minimum brings back is not reported (it is exactly what release means may happen).
             */
            released?: {
                [key: string]: number;
            };
            /** @description A full problem instance. */
            scenario?: components["schemas"]["Scenario"] | null;
            /**
             * Scenario Id
             * @description Slug of a curated scenario. Provide this or `scenario`; `scenario` wins when both are set.
             */
            scenario_id?: string | null;
            /** @description The schedule that solve returned. */
            schedule: components["schemas"]["Schedule"];
        };
        /** ExplainResponse */
        ExplainResponse: {
            report: components["schemas"]["ExplanationReport"];
        };
        /**
         * ExplanationReport
         * @description Everything explainable about one solve result relative to what the user asked for.
         *     Computed from the submitted :class:`SolvePreferences` and the resulting
         *     :class:`Schedule` — no re-solve, so nothing here can disagree with the plan already on
         *     screen.
         */
        ExplanationReport: {
            /**
             * Budget Exhausted
             * @description True if the budget ran out before every dropped edit could be explained — the remainder are reported `not_determined`, never silently omitted.
             * @default false
             */
            budget_exhausted: boolean;
            /**
             * Budget S
             * @description The overall wall-clock budget this report ran under.
             */
            budget_s: number;
            /** Edits */
            edits?: components["schemas"]["EditExplanation"][];
            /** Reinstated */
            reinstated?: components["schemas"]["ReinstatedService"][];
            /** Ripple */
            ripple?: components["schemas"]["RippleMove"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Mower */
        Mower: {
            /**
             * Area Capacity M2 Per Day
             * @description Mowing rate. Promoted from the generator source (ADR-0024); None for scenarios authored before that. Feeds the default per-(area, mower) duration and the recomputed load factor.
             */
            area_capacity_m2_per_day?: number | null;
            /**
             * Can Mow
             * @description Names of areas this mower is able to service.
             */
            can_mow: string[];
            /**
             * Model
             * @description Mower model label. Promoted from the generator source (ADR-0024); None for scenarios authored before that. Display + catalogue lookup only.
             */
            model?: string | null;
            /** Name */
            name: string;
        };
        /**
         * PreferenceAgreement
         * @description Overall agreement plus the same counts split by :attr:`PreferredTask.origin` —
         *     "7 of 9 frozen tasks untouched" is the sentence the UI wants to write.
         */
        PreferenceAgreement: {
            /** By Origin */
            by_origin?: {
                [key: string]: components["schemas"]["AgreementCounts"];
            };
            /**
             * Mower Kept
             * @default 0
             */
            mower_kept: number;
            /**
             * Mower Total
             * @default 0
             */
            mower_total: number;
            /**
             * Time Kept
             * @default 0
             */
            time_kept: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * PreferenceReport
         * @description What the re-solve did with the user's edits. Attached to :class:`SolveResult`.
         */
        PreferenceReport: {
            agreement: components["schemas"]["PreferenceAgreement"];
            /** Dropped */
            dropped?: components["schemas"]["DroppedPreference"][];
            /**
             * Level
             * @description The stability setting this solve actually ran at; None in heuristic mode, which biases the search and leaves the objective alone. Echoed because `Schedule.cost`'s shape depends on it — at 'top' the unmet-preference count is a separate leading slot, at the others it is summed into an existing service-quality slot and cannot be split back out.
             */
            level?: ("top" | "high" | "low" | "avoid" | "tiebreak") | null;
            /**
             * Pref Level
             * @description The `-c pref_level=N` constant `level` maps to, for the expert readout. None whenever `level` is.
             */
            pref_level?: number | null;
        };
        /**
         * PreferredTask
         * @description One task the user edited or froze; a re-solve should try to preserve it (ADR-0031).
         *
         *     Deliberately **index-free**. The encoding numbers an area's tasks 1..N in time order
         *     (``task(A,1..M)``, ordered by ``start(A,N+1) >= completion(A,N)``), so a preference
         *     phrased as "task 3 of this area" silently re-targets the moment the solver picks a
         *     different ``num_starts``. "This area has a task starting at hour S, on mower M"
         *     survives that, and is what the user actually meant by dragging a bar.
         *
         *     The two halves are scored independently, so ``mower=None`` is meaningful on its own:
         *     a **time-only** preference — keep the hour, let the solver choose the mower. The
         *     Iteration 5 schedule editor always names a mower; the field is optional because that
         *     is the shape a later mower-breakdown control needs, and it costs nothing to allow.
         */
        PreferredTask: {
            /** Area */
            area: string;
            /**
             * Mower
             * @description Preferred mower; None means 'keep the time, any mower'.
             */
            mower?: string | null;
            /**
             * Origin
             * @description Where the preference came from. Read by the UI and the mechanism study only — it is never emitted as a solver fact.
             * @default edited
             * @enum {string}
             */
            origin: "frozen" | "edited" | "added";
            /**
             * Start
             * @description Start hour offset from t = 0, as in ScheduledTask.
             */
            start: number;
        };
        /**
         * ReinstatedService
         * @description An area whose schedule carries more tasks than its *baseline* named for it —
         *     services the solver added beyond what the plan before the re-solve already had.
         *     Invisible to the kept/dropped count (there is no negative preference, ADR-0035
         *     decision 3: release means "out of the payload", not "never do this"), so this is the
         *     one explanation class that needs no dropped edit to trigger.
         *
         *     A released service brought straight back by the area's own service-count minimum is
         *     *not* reported — that is exactly what release means may happen, not a mismatch to
         *     explain (amendment, 2026-09-24: ``submitted_count`` folds in whatever was released from
         *     the area, so the baseline is the plan before the re-solve, not the payload alone).
         */
        ReinstatedService: {
            /** Actual Count */
            actual_count: number;
            /** Area */
            area: string;
            /**
             * Forced By Minimum
             * @description Whether the area's service-count minimum actually required the extra service (``submitted_count < min_services``). When False the minimum was already met and the solver added it for its own reasons — the max-interval objective, typically. The UI must not name the minimum as the cause in that case.
             * @default false
             */
            forced_by_minimum: boolean;
            /** Min Services */
            min_services: number;
            /**
             * Submitted Count
             * @description The plan before this re-solve: the payload's count for this area plus whatever was released from it. Not literally 'submitted' any more — kept the name since the frontend and ADR-0048 already read it that way.
             */
            submitted_count: number;
        };
        /**
         * RippleMove
         * @description A *frozen* task — one the user did not touch — that still moved, attributed when
         *     possible to sharing a mower or area with one of the user's edits.
         */
        RippleMove: {
            /** Area */
            area: string;
            /** Mower */
            mower?: string | null;
            /**
             * Shares Area With
             * @description Set when this task's own area was edited elsewhere.
             */
            shares_area_with?: string | null;
            /**
             * Shares Mower With
             * @description Area name of an edited task using the same mower.
             */
            shares_mower_with?: string | null;
            /** Start */
            start: number;
        };
        /**
         * RollRequest
         * @description Body for ``POST /api/scenario/advance`` — the moving-horizon step (ADR-0042).
         *
         *     Advance "now" by ``hours``, given the plan ``tasks`` that were executed. There is no
         *     execution simulation: ``tasks`` is just the current plan. ``hours`` out of the
         *     ``1..horizon_hours`` range is a 400.
         */
        RollRequest: {
            /**
             * Hours
             * @description How far to advance now, in whole hours.
             * @default 24
             */
            hours: number;
            scenario: components["schemas"]["Scenario"];
            /**
             * Tasks
             * @description The plan being executed over the elapsed window.
             */
            tasks?: components["schemas"]["ScheduledTask"][];
        };
        /**
         * RollResponse
         * @description What ``POST /api/scenario/advance`` returns: the rolled scenario (with its derived
         *     figures recomputed, like every other scenario response) plus what the roll did.
         */
        RollResponse: {
            /**
             * Carried
             * @description Still-future tasks rebased to the new now, as frozen re-solve preferences.
             */
            carried: components["schemas"]["PreferredTask"][];
            /**
             * Consumed
             * @description New history events from now-past tasks — one per area serviced in the window.
             */
            consumed: components["schemas"]["ServiceEvent"][];
            derived: components["schemas"]["ScenarioDerived"];
            /**
             * Notes
             * @description Remarks about this roll (areas idle, services straddling now).
             */
            notes: string[];
            scenario: components["schemas"]["Scenario"];
        };
        /**
         * Scenario
         * @description A complete planning problem instance.
         */
        Scenario: {
            /** Areas */
            areas: components["schemas"]["Area"][];
            /**
             * Base Durations
             * @description Data-driven per-(area, mower) base mowing hours (ADR-0013). When set, the completion table uses these instead of sampling.
             */
            base_durations?: components["schemas"]["BaseDuration"][] | null;
            /**
             * Duration Seed
             * @description Seed for the (otherwise deterministic) mowing-duration sampling. Ignored when base_durations is set.
             * @default 0
             */
            duration_seed: number;
            /** History */
            history: components["schemas"]["ServiceEvent"][];
            /**
             * Horizon Hours
             * @default 168
             */
            horizon_hours: number;
            /**
             * Horizon Start Hour
             * @description Hour of the week (0 = Mon 00:00) that t = 0 corresponds to.
             * @default 13
             */
            horizon_start_hour: number;
            /** Mowers */
            mowers: components["schemas"]["Mower"][];
            /** Name */
            name: string;
        };
        /** ScenarioBundle */
        ScenarioBundle: {
            derived: components["schemas"]["ScenarioDerived"];
            scenario: components["schemas"]["Scenario"];
        };
        /**
         * ScenarioCreateRequest
         * @description Body for ``POST /api/scenarios`` — save the edited scenario under a *new* slug
         *     (ADR-0026). ``id`` is the target slug; a clash is a 409. ``PUT /api/scenario/{id}``
         *     is the overwrite path and takes the bare ``Scenario`` instead.
         */
        ScenarioCreateRequest: {
            /**
             * Id
             * @description Target slug (lowercase, digits, internal hyphens).
             */
            id: string;
            scenario: components["schemas"]["Scenario"];
        };
        /**
         * ScenarioDerived
         * @description Figures computed from the ``Scenario`` — never stored, recomputed on every edit
         *     (ADR-0024, ``fleetplanning.derived``). Replaces the old source-derived ``detail``.
         */
        ScenarioDerived: {
            /**
             * Bounds
             * @description Per-area (min, max) service starts for the week — the user-owned requirement when set, else the ADR-0017 derivation.
             */
            bounds: {
                [key: string]: [
                    number,
                    number
                ];
            };
            /**
             * Load Factor
             * @description Demand/capacity proxy; None without size/rate data.
             */
            load_factor?: number | null;
        };
        /** ScenarioListEntry */
        ScenarioListEntry: {
            /** Id */
            id: string;
            summary: components["schemas"]["ScenarioSummary"];
        };
        /**
         * ScenarioSummary
         * @description The facts the picker shows next to a scenario name — all computed, never stored.
         */
        ScenarioSummary: {
            /** Areas */
            areas: number;
            /** Holes */
            holes: number;
            /**
             * Load Factor
             * @description Demand/capacity proxy, recomputed from the scenario (ADR-0024); None when size or mower-rate data is missing.
             */
            load_factor?: number | null;
            /** Mowers */
            mowers: number;
        };
        /**
         * ScenarioTemplateRequest
         * @description Body for ``POST /api/scenario/template`` (ADR-0027). ``name`` seeds the editable
         *     scenario-name field only — it is not a slug and nothing is written; Save derives the
         *     slug from it later.
         */
        ScenarioTemplateRequest: {
            /**
             * Name
             * @default new-scenario
             */
            name: string;
        };
        /** Schedule */
        Schedule: {
            /**
             * Cost
             * @description clingcon optimisation cost vector (lexicographic).
             */
            cost: number[];
            /** Tasks */
            tasks: components["schemas"]["ScheduledTask"][];
            /** Violations */
            violations: components["schemas"]["Violation"][];
        };
        /** ScheduledTask */
        ScheduledTask: {
            /** Area */
            area: string;
            /** End */
            end: number;
            /** Mower */
            mower: string;
            /** Start */
            start: number;
            /** Task */
            task: number;
        };
        /**
         * ServiceEvent
         * @description One past (or in-progress) service, relative to t = 0.
         */
        ServiceEvent: {
            /** Area */
            area: string;
            /** Completion */
            completion: number;
            /** Mower */
            mower: string;
            /** Start */
            start: number;
        };
        /**
         * SolveJobStarted
         * @description ``POST /api/solve`` returns this immediately — the solve keeps running in the
         *     background (ADR-0022, anytime solving). Poll ``GET /api/solve/{job_id}`` for progress.
         */
        SolveJobStarted: {
            /** Job Id */
            job_id: string;
        };
        /**
         * SolveJobStatus
         * @description Response for both the poll and cancel endpoints.
         *
         *     ``result`` is ``None`` only while running with no model found yet; while running with
         *     a model it is the best-so-far (``solved=True, optimal=False``); once ``done`` it is
         *     the final result (possibly still ``solved=False`` — no feasible schedule was found).
         */
        SolveJobStatus: {
            /** Done */
            done: boolean;
            /** Job Id */
            job_id: string;
            result?: components["schemas"]["SolveResult"] | null;
        };
        /**
         * SolvePreferences
         * @description The edited/frozen tasks a re-solve should try to preserve, and how (ADR-0031).
         *
         *     ``mode="off"`` (the default) means the solve is byte-identical to one with no
         *     preferences at all: no extra program, no extra flag. That invariant is what keeps
         *     every existing golden and contract test meaningful.
         */
        SolvePreferences: {
            /**
             * Level
             * @description Weak mode only: where the preference weak constraints sit relative to the forward model's own service-quality levels, i.e. what one churned task is worth. 'top' outranks every service violation (the default); 'high' ties it with one missed High-priority service, 'low' with a Low-priority one, 'avoid' with an hour worked in an avoid window; 'tiebreak' puts it below all of them. Prefer 'top' — ADR-0034 found 'tiebreak' indistinguishable from ignoring the edits (0.131 vs 0.134 agreement) on any instance the solver cannot prove within budget, which is most of them. It is kept for the study, not as a product option.
             * @default top
             * @enum {string}
             */
            level: "top" | "high" | "low" | "avoid" | "tiebreak";
            /**
             * Mode
             * @description How preferences reach the solver: 'weak' adds weak constraints at their own priority level, 'heuristic' adds #heuristic directives (ADR-0032). 'off' ignores `tasks` entirely.
             * @default off
             * @enum {string}
             */
            mode: "off" | "weak" | "heuristic";
            /** Tasks */
            tasks?: components["schemas"]["PreferredTask"][];
        };
        /** SolveRequest */
        SolveRequest: {
            /**
             * Clingo Args
             * @description Expert-mode override for the clingo command line, replacing the default -t4 --configuration=many portfolio (ADR-0007, ADR-0023). Omit for the default. Must not set constants (-c/--const) — the horizon constant is appended automatically; clingo itself rejects most other invalid flags/values, surfaced as a 400.
             */
            clingo_args?: string[] | null;
            /** @description User edits to preserve on a re-solve (ADR-0031). Omit for a cold solve; omitting it and sending `mode: off` are equivalent, and both leave the solver program exactly as it would be without this feature. */
            preferences?: components["schemas"]["SolvePreferences"] | null;
            /** @description A full (edited) problem instance, solved directly (ADR-0024). Every `model.py` rule runs during request parsing, so a malformed body is a 422 with a field path. Takes precedence over `scenario_id`. */
            scenario?: components["schemas"]["Scenario"] | null;
            /**
             * Scenario Id
             * @description Slug of a curated scenario (see GET /api/scenarios). Provide this or `scenario`; `scenario` wins when both are set.
             */
            scenario_id?: string | null;
            /**
             * Time Limit S
             * @description Solver wall-clock budget in seconds; on timeout the best schedule so far is returned. Capped at 4 hours purely as a sanity limit against runaway jobs.
             * @default 20
             */
            time_limit_s: number;
        };
        /** SolveResult */
        SolveResult: {
            /** Horizon Hours */
            horizon_hours: number;
            /**
             * Optimal
             * @description True if the solver proved optimality; False if it returned a best-so-far.
             * @default false
             */
            optimal: boolean;
            /** @description What became of the user's schedule edits (ADR-0031). None when the solve carried no preferences. */
            preferences?: components["schemas"]["PreferenceReport"] | null;
            /**
             * Quality
             * @description The fixed 5-slot service-quality vector [max@P1, max@P2, max@P3, avoid, min] recomputed by solver/score.py (ADR-0016). Unlike the raw clingcon `schedule.cost`, its length and meaning do not change with the instance or the preference level, so it is the axis to compare across solves — a rolling horizon compares it across rolls (ADR-0042). None when there is no schedule.
             */
            quality?: number[] | null;
            /** Scenario Name */
            scenario_name: string;
            schedule?: components["schemas"]["Schedule"] | null;
            /** Solve Time S */
            solve_time_s: number;
            /** Solved */
            solved: boolean;
            /** @description Solver configuration for this solve — expert-mode diagnostics. None only for results not produced by a real solve (e.g. stubbed in tests). */
            solver?: components["schemas"]["SolverInfo"] | null;
            /**
             * Status
             * @description optimal | satisfiable | unsatisfiable | unknown (see ADR-0010).
             * @default unknown
             */
            status: string;
        };
        /**
         * SolverInfo
         * @description How the solver was configured for one solve — expert-mode diagnostics, not
         *     end-user data.
         *
         *     Echoed to the client so the UI reports the real configuration instead of a hardcoded
         *     guess (an earlier frontend string claimed "single-threaded"; the default portfolio
         *     is 4-thread — see ADR-0007, ADR-0009).
         */
        SolverInfo: {
            /**
             * Args
             * @description Thread/portfolio flags passed to clingo (ADR-0007). Excludes the -c horizon=N instance constant.
             */
            args: string[];
            /**
             * Config
             * @description clingo --configuration, present only when threads > 1.
             */
            config?: string | null;
            /**
             * Name
             * @default clingcon
             */
            name: string;
            /** Threads */
            threads: number;
            /** Time Limit S */
            time_limit_s: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Violation */
        Violation: {
            /** Area */
            area: string;
            /**
             * Kind
             * @description max_interval | min_interval | avoid_zone
             */
            kind: string;
            /**
             * Since
             * @description Hour offset from t=0 when this max-interval violation's elapsed window began — the latest moment the area could still have been serviced on time. Set only for a violation with a concrete window inside this horizon (a gap between two scheduled tasks, or the first task starting too late against service history); None for every other violation kind, and for the last-task-too-early wraparound case, whose 'violation' is a risk into next week's cycle rather than an elapsed window this week.
             */
            since?: number | null;
            /** Task */
            task?: number | null;
            /**
             * Until
             * @description Hour offset when the elapsed window named in `since` ended — the start of the task that finally serviced the area. None under the same conditions as `since`.
             */
            until?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    post_explain_api_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    post_scenario_advance_api_scenario_advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_scenario_derived_api_scenario_derived_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Scenario"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDerived"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_scenario_template_api_scenario_template_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_api_scenario__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_scenario_api_scenario__scenario_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Scenario"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_api_scenario__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListEntry"][];
                };
            };
        };
    };
    create_scenario_api_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_solve_api_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveJobStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_solve_api_solve__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cancel_solve_api_solve__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
